import { useState } from "react";
import { FiChevronDown } from "react-icons/fi";

const faqs = [
  {
    question: "What is ResumeAI?",
    answer:
      "ResumeAI is an AI-powered resume analyzer that evaluates your resume, provides ATS scores, identifies missing keywords, and suggests improvements to increase your chances of getting interviews.",
  },
  {
    question: "Which file formats are supported?",
    answer:
      "You can upload resumes in PDF and DOCX formats. Our AI automatically extracts and analyzes the content from your resume.",
  },
  {
    question: "How is the ATS score calculated?",
    answer:
      "The ATS score is generated by analyzing resume formatting, keyword optimization, readability, section structure, and relevance to industry standards.",
  },
  {
    question: "Is my resume stored securely?",
    answer:
      "Yes. Your resumes are protected using secure authentication and encrypted storage. Only you can access your uploaded files.",
  },
  {
    question: "Can I compare my resume with a job description?",
    answer:
      "Yes. ResumeAI can compare your resume against a job description and highlight missing skills, keywords, and optimization opportunities.",
  },
  {
    question: "Does ResumeAI use Artificial Intelligence?",
    answer:
      "Yes. Our platform uses advanced AI models to analyze resumes, identify weaknesses, and generate personalized recommendations.",
  },
  {
    question: "Can I download my analysis report?",
    answer:
      "Absolutely. You can download your ATS report, improvement suggestions, and resume insights for future reference.",
  },
  {
    question: "Is ResumeAI free?",
    answer:
      "ResumeAI offers free features for resume analysis along with premium plans that unlock advanced AI tools and detailed reports.",
  },
];

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState(0);

  return (
    <section className="relative py-24">
      <div className="mx-auto max-w-5xl px-6">

        {/* Heading */}

        <div className="mb-16 text-center">

          <span className="rounded-full border border-violet-500/20 bg-violet-500/10 px-4 py-2 text-sm font-medium text-violet-300">
            Frequently Asked Questions
          </span>

          <h2 className="mt-6 text-4xl font-black text-white md:text-5xl">
            Got Questions?
            <span className="bg-gradient-to-r from-violet-500 to-cyan-400 bg-clip-text text-transparent">
              {" "}
              We've Got Answers
            </span>
          </h2>

          <p className="mx-auto mt-6 max-w-2xl text-lg text-gray-400">
            Everything you need to know about ResumeAI,
            ATS optimization, AI analysis, and resume building.
          </p>

        </div>

        {/* FAQ */}

        <div className="space-y-5">

          {faqs.map((faq, index) => (
            <div
              key={index}
              className="overflow-hidden rounded-3xl border border-white/10 bg-white/5 backdrop-blur-xl transition hover:border-violet-500/30"
            >

              {/* Question */}

              <button
                onClick={() =>
                  setOpenIndex(openIndex === index ? -1 : index)
                }
                className="flex w-full items-center justify-between p-7 text-left"
              >
                <span className="text-lg font-semibold text-white">
                  {faq.question}
                </span>

                <FiChevronDown
                  className={`text-2xl text-violet-400 transition-transform duration-300 ${
                    openIndex === index ? "rotate-180" : ""
                  }`}
                />
              </button>

              {/* Answer */}

              <div
                className={`grid transition-all duration-300 ${
                  openIndex === index
                    ? "grid-rows-[1fr]"
                    : "grid-rows-[0fr]"
                }`}
              >
                <div className="overflow-hidden">
                  <p className="px-7 pb-7 leading-8 text-gray-400">
                    {faq.answer}
                  </p>
                </div>
              </div>

            </div>
          ))}

        </div>

      </div>
    </section>
  );
}